**Полезные методы в Pandas**

In [8]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv("/content/drive/MyDrive/Data/tips.csv")

In [10]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [11]:
str(3560325168603410)[-4:]

'3410'

In [12]:
def last_four(num):
  return str(num)[-4:]

In [13]:
last_four(6011812112971322)

'1322'

In [14]:
df["last_four"] = df["CC Number"].apply(last_four)

In [15]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221

In [16]:
df["total_bill"].mean()

np.float64(19.78594262295082)

In [17]:
def yelp(price):
  if price < 10:
    return '$'
  elif price >= 10 and price < 30:
    return '$$'
  else:
    return '$$$'

In [18]:
df["yelp"] = df["total_bill"].apply(yelp)

In [19]:
df["yelp"]

0      $$
1      $$
2      $$
3      $$
4      $$
       ..
239    $$
240    $$
241    $$
242    $$
243    $$
Name: yelp, Length: 244, dtype: object

In [20]:
def simple(num):
  return num*2

In [21]:
lambda num: num*2

In [23]:
df["total_bill"].apply(lambda num: num*2)

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [24]:
def quality(total_bill, tip):
  if tip / total_bill > 0.25:
    return "Щедрые чаевые"
  else:
    return "Обычные чаевые"

In [25]:
quality(16.99, 1.01)

'Обычные чаевые'

In [27]:
df["quality"] = df[["total_bill", "tip"]].apply(lambda df: quality(df["total_bill"], df["tip"]), axis=1)

In [28]:
df["quality"] = np.vectorize(quality)(df["total_bill"], df["tip"])

In [29]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four,yelp,quality
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410,$$,Обычные чаевые
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230,$$,Обычные чаевые
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322,$$,Обычные чаевые
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994,$$,Обычные чаевые
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221,$$,Обычные чаевые

In [30]:
df = pd.read_csv("/content/drive/MyDrive/Data/tips.csv")

In [31]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [33]:
df.sort_values("tip", ascending=False)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
...,...,...,...,...,...,...,...,...,...,...,...
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032

In [34]:
df.sort_values(["tip", "size"])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954

In [35]:
df["total_bill"].max()

50.81

In [36]:
df["total_bill"].idxmax()

170

In [40]:
df.iloc[df["total_bill"].idxmin()]

total_bill                      3.07
tip                              1.0
sex                           Female
smoker                           Yes
day                              Sat
time                          Dinner
size                               1
price_per_person                3.07
Payer Name             Tiffany Brock
CC Number           4359488526995267
Payment ID                   Sat3455
Name: 67, dtype: object

In [41]:
df.corr(numeric_only=True)

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [43]:
df["sex"].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [44]:
df["day"].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [45]:
df["day"].nunique()

4

In [47]:
df["sex"].replace(["Female", "Male"], ["F", "M"])

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [48]:
my_map = {"Female": "F", "Male": "M"}

In [49]:
df["sex"].map(my_map)

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [52]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [53]:
simple_df = pd.DataFrame([1, 2, 2, 2], ['a', 'b', 'c', 'd'])

In [54]:
simple_df.duplicated()

a    False
b    False
c     True
d     True
dtype: bool

In [55]:
simple_df.drop_duplicates()

   0
a  1
b  2

In [59]:
df[df["total_bill"].between(10, 20, inclusive="both")]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,566287581219,Sun2546
...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4097938155941930,Sat7220
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,Sat4615
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [61]:
df.nlargest(2, "tip")

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.0,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.0,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [62]:
df.sort_values("tip", ascending=False).iloc[0:2]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.0,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.0,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [63]:
df.nsmallest(2, "tip")

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.0,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
92,5.75,1.0,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780

In [66]:
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
233,10.77,1.47,Male,No,Sat,Dinner,2,5.38,Paul Novak,6011698897610858,Sat1467
151,13.13,2.00,Male,No,Sun,Dinner,2,6.56,Jason Arnold,3571825125296106,Sun2127
15,21.58,3.92,Male,No,Sun,Dinner,2,10.79,Matthew Reilly,180073029785069,Sun1878
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903

In [69]:
df.sample(frac=0.1)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,503857080488,Thur3948
45,18.29,3.00,Male,No,Sun,Dinner,2,9.14,Richard Fitzgerald,375156610762053,Sun8643
54,25.56,4.34,Male,No,Sun,Dinner,4,6.39,Ronald Owens,6569607991983380,Sun9470
26,13.37,2.00,Male,No,Sat,Dinner,2,6.68,Kyle Avery,6531339539615499,Sat6651
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,Sat4505
224,13.42,1.58,Male,Yes,Fri,Lunch,2,6.71,Ronald Vaughn DVM,341503466406403,Fri5959
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3572865915176463,Sun591
176,17.89,2.00,Male,Yes,Sun,Dinner,2,8.94,Walter Simmons,6011481578696110,Sun5961
106,20.49,4.06,Male,Yes,Sat,Dinner,2,10.24,Karl Mcdaniel,180024452771522,Sat7865
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
164,17.51,3.00,Female,Yes,Sun,Dinner,2,8.76,Audrey Griffin,3500853929693258,Sun444
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
94,22.75,3.25,Female,No,Fri,Dinner,2,11.38,Jamie Garza,676318332068,Fri2318
222,8.58,1.92,Male,Yes,Fri,Lunch,1,8.58,Jason Lawrence,3505302934650403,Fri6624
51,10.29,2.60,Female,No,Sun,Dinner,2,5.14,Jessica Ibarra,4999759463713,Sun4474
97,12.03,1.50,Male,Yes,Fri,Dinner,2,6.02,Eric Herrera,580116092652,Fri9268
135,8.51,1.25,Female,No,Thur,Lunch,2,4.26,Rebecca Harris,4320272020376174,Thur6600
188,18.15,3.50,Female,Yes,Sun,Dinner,3,6.05,Glenda Wiggins,578329325307,Sun430
134,18.26,3.25,Female,No,Thur,Lunch,2,9.13,Karen Rodriguez,4952604748911,Thur75
83,32.68,5.00,Male,Yes,Thur,Lunch,2,16.34,Daniel Murphy,5356177501009133,Thur8801
158,13.39,2.61,Female,No,Sun,Dinner,2,6.70,Ashley Boyd,3571088058115021,Sun982